// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrnznosfclfepqdxyhjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impybnpub3NmY2xmZXBxZHh5aGpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwMDYyODUsImV4cCI6MjA1MjU4MjI4NX0._l-RObKhi7zTIFR0zHSfHG9JLkv9-khFVE8G7akjHDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);